  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
      viagem-consumer:
        condition: service_started
      viagem-producer:
        condition: service_started
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: iot
    volumes:
      - ./tests:/app/tests
    command: >
      sh -c "sleep 5 && pytest /app/tests/integration/test_kafka_integration.py /app/tests/e2e/test_full_pipeline.py"
