FROM python:3.11-slim

# Instala Poetry
RUN pip install poetry

WORKDIR /app
COPY pyproject.toml poetry.lock* /app/

# Instala dependências com Poetry
RUN poetry config virtualenvs.create false \
    && poetry install --no-interaction --no-ansi --no-root

RUN apt-get update && \
    apt-get install -y iputils-ping netcat-openbsd && \
    rm -rf /var/lib/apt/lists/*

COPY . /app

ENV PYTHONPATH=/app

CMD ["python", "src/producer/run_simulador.py"]