FROM python:3.11-slim

WORKDIR /app

# Instala dependências do sistema para psycopg2-binary e ferramentas de rede
RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc libpq-dev curl netcat-openbsd iputils-ping && \
    rm -rf /var/lib/apt/lists/*

# Instala wait-for-it.sh para espera de serviços
RUN curl -sSL https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh -o /usr/bin/wait-for-it.sh && \
    chmod +x /usr/bin/wait-for-it.sh

# Instala Poetry e o adiciona ao PATH
ENV POETRY_VERSION=1.8.2
RUN curl -sSL https://install.python-poetry.org | python3 - && \
    ln -s /root/.local/bin/poetry /usr/local/bin/poetry

# Desabilita criação de venv interna pelo Poetry
ENV POETRY_VIRTUALENVS_CREATE=false

# Copia e instala todas as dependências do projeto, incluindo as de desenvolvimento
COPY pyproject.toml poetry.lock ./
RUN poetry install --no-root --no-interaction --no-ansi