services:
  # O serviço test-runner é o que executa seus testes Pytest
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test # Será criado abaixo
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
      viagem-consumer:
        condition: service_started
      viagem-producer:
        condition: service_started
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: iot
    volumes:
      - ./tests:/app/tests
      - ./src:/app/src # Adicionado para que o test-runner possa importar o código do projeto
      - ./config:/app/config # Adicionado
    # Usamos 'command' para esperar por Kafka e Postgres via wait-for-it, e então rodar pytest
    command: >
      sh -c "/usr/bin/wait-for-it.sh kafka:29092 --timeout=60 --strict -- \
            /usr/bin/wait-for-it.sh postgres:5432 --timeout=60 --strict -- \
            pytest /app/tests/integration/test_kafka_integration.py /app/tests/e2e/test_full_pipeline.py"
    networks:
      - kafka-network # O test-runner também precisa estar na rede kafka-network